### ISSUE TITLE
오류가 많군요

### ISSUE THREAD

**Issue by piese1028** [SaidBySolo/auto-self-diagnosis#31]
![image](https://user-images.githubusercontent.com/61900596/109502140-f0203080-7adb-11eb-8c5c-da4150cd928b.png)
Traceback (most recent call last):
  File "C:\Users\JUNGWONYOUNG\Desktop\auto-self-diagnosis-master\auto-self-diagnosis.py", line 91, in <module>
    driver.find_element_by_xpath('//*[@id="btnConfirm"]').click()
  File "C:\Users\JUNGWONYOUNG\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\JUNGWONYOUNG\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\JUNGWONYOUNG\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\JUNGWONYOUNG\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input data-v-7c3d7466="" type="submit" id="btnConfirm" value="확인 / Confirm"> is not clickable at point (951, 866). Other element would receive the click: <div data-v-73706766="" class="privacy_con">...</div>
  (Session info: headless chrome=88.0.4324.190)

**Comment by piese1028** [comment]
신학기로 자가진단 계정을 새로 가입해야해서 오류가 생긴 것 같습니다
